schema_version = "1.0.0"

id = "shapekey_keeper"
version = "1.8.1"
name = "SKkeeper"
tagline = "Applies modifiers while keeping shapekeys and drivers"
maintainer = "Johannes Rauch"
type = "add-on"
website = "https://github.com/smokejohn/SKkeeper"
tags = ["Object"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/.github/",
  "/.gitignore",
  "/*.zip",
  "/tests",
  "/images",
  "/build.sh"
]
